### ISSUE TITLE
Fix index error when calling nums.add()

### ISSUE THREAD

**Issue by jayrajmulani** [jayrajmulani/group2-se-homeworks#11]
Error traceback for reference:
```
Traceback (most recent call last):
  File "/Users/jayraj/Documents/Homeworks/SE/group2-se-homeworks/code/main.py", line 21, in <module>
    populate_num()
  File "/Users/jayraj/Documents/Homeworks/SE/group2-se-homeworks/code/main.py", line 16, in populate_num
    n.add(i)
  File "/Users/jayraj/Documents/Homeworks/SE/group2-se-homeworks/code/num.py", line 41, in add
    self._has[pos] = v
IndexError: list assignment index out of range
```

**Comment by jayrajmulani** [comment]
Fixed the issue by modifying the if condition in `nums.py:add` method. append method was needed until the maximum number of element `nums` were filled, since python lists are dynamic and allocates memory as we keep appending elements.
